project_id = "abppifmnwdhlzcgiodho"

[functions.weekly-digest]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-usage]
verify_jwt = true

[functions.increment-usage]
verify_jwt = true